services:
  api:
    image: 844486820561.dkr.ecr.ap-south-1.amazonaws.com/atmos-core:latest
    container_name: atmos-api
    env_file: .env
    ports:
      - "8080:8080"
    restart: unless-stopped
