services:
  api:
    image: 844486820561.dkr.ecr.ap-south-1.amazonaws.com/atmos-core:latest
    container_name: atmos-api
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/atmos-firebase.json:/secrets/atmos-firebase.json:ro
    restart: unless-stopped

  worker:
    image: 844486820561.dkr.ecr.ap-south-1.amazonaws.com/atmos-core:latest
    container_name: atmos-worker
    env_file: .env
    command: ./worker
    volumes:
      - /home/ubuntu/atmos-firebase.json:/secrets/atmos-firebase.json:ro
    restart: unless-stopped
